/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as SolucoesRaioxDaFaturaRouteImport } from './routes/solucoes.raiox-da-fatura'
import { Route as SolucoesWorkflowProfissionaisRouteImport } from './routes/solucoes.workflow-profissionais'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRaioxDaFaturaRoute = SolucoesRaioxDaFaturaRouteImport.update({
  id: '/solucoes/raiox-da-fatura',
  path: '/solucoes/raiox-da-fatura',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesWorkflowProfissionaisRoute =
  SolucoesWorkflowProfissionaisRouteImport.update({
    id: '/solucoes/workflow-profissionais',
    path: '/solucoes/workflow-profissionais',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workflow': typeof WorkflowRoute
  '/solucoes/raiox-da-fatura': typeof SolucoesRaioxDaFaturaRoute
  '/solucoes/workflow-profissionais': typeof SolucoesWorkflowProfissionaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workflow': typeof WorkflowRoute
  '/solucoes/raiox-da-fatura': typeof SolucoesRaioxDaFaturaRoute
  '/solucoes/workflow-profissionais': typeof SolucoesWorkflowProfissionaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workflow': typeof WorkflowRoute
  '/solucoes/raiox-da-fatura': typeof SolucoesRaioxDaFaturaRoute
  '/solucoes/workflow-profissionais': typeof SolucoesWorkflowProfissionaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workflow'
    | '/solucoes/raiox-da-fatura'
    | '/solucoes/workflow-profissionais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workflow'
    | '/solucoes/raiox-da-fatura'
    | '/solucoes/workflow-profissionais'
  id:
    | '__root__'
    | '/'
    | '/workflow'
    | '/solucoes/raiox-da-fatura'
    | '/solucoes/workflow-profissionais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkflowRoute: typeof WorkflowRoute
  SolucoesRaioxDaFaturaRoute: typeof SolucoesRaioxDaFaturaRoute
  SolucoesWorkflowProfissionaisRoute: typeof SolucoesWorkflowProfissionaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/raiox-da-fatura': {
      id: '/solucoes/raiox-da-fatura'
      path: '/solucoes/raiox-da-fatura'
      fullPath: '/solucoes/raiox-da-fatura'
      preLoaderRoute: typeof SolucoesRaioxDaFaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/workflow-profissionais': {
      id: '/solucoes/workflow-profissionais'
      path: '/solucoes/workflow-profissionais'
      fullPath: '/solucoes/workflow-profissionais'
      preLoaderRoute: typeof SolucoesWorkflowProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkflowRoute: WorkflowRoute,
  SolucoesRaioxDaFaturaRoute: SolucoesRaioxDaFaturaRoute,
  SolucoesWorkflowProfissionaisRoute: SolucoesWorkflowProfissionaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
