/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucoesWorkflowProfissionaisRouteImport } from './routes/solucoes.workflow-profissionais'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesWorkflowProfissionaisRoute =
  SolucoesWorkflowProfissionaisRouteImport.update({
    id: '/solucoes/workflow-profissionais',
    path: '/solucoes/workflow-profissionais',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/solucoes/workflow-profissionais': typeof SolucoesWorkflowProfissionaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/solucoes/workflow-profissionais': typeof SolucoesWorkflowProfissionaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/solucoes/workflow-profissionais': typeof SolucoesWorkflowProfissionaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/solucoes/workflow-profissionais'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/solucoes/workflow-profissionais'
  id: '__root__' | '/' | '/solucoes/workflow-profissionais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SolucoesWorkflowProfissionaisRoute: typeof SolucoesWorkflowProfissionaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/workflow-profissionais': {
      id: '/solucoes/workflow-profissionais'
      path: '/solucoes/workflow-profissionais'
      fullPath: '/solucoes/workflow-profissionais'
      preLoaderRoute: typeof SolucoesWorkflowProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SolucoesWorkflowProfissionaisRoute: SolucoesWorkflowProfissionaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
